### ISSUE TITLE
Cannot compile on ubuntu, missing dependencies

### ISSUE THREAD

**Issue by stefangeorg** [vibansal/ancestry#1]
There is no Lbsgsb3.0 folder, I've tried finding this exact folder online, but doesn't seem to exist anywhere. Can this be included or a link to that library be included?

**Comment by bpow** [comment]
I am running into the same problem. My suspicion is that it is something like the code at http://users.iems.northwestern.edu/~nocedal/Software/Lbfgsb.3.0.tar.gz but translated using f2c. However, I'm not sure if that is the case or if so how it was done.

Any comments from the authors?

**Comment by vibansal** [comment]
I have added the missing files to the repository. I apologize for the delay in responding.
