### ISSUE TITLE
Does this tool involve seeding?

### ISSUE THREAD

**Issue by djmce** [vibansal/ancestry#10]
Does this tool involve some kind of random seeding or do you expect it to produce identical results each time it is run with the same input data?

**Comment by vibansal** [comment]
The admixture coefficients are initialized with random values, therefore, the tool may not produce the exact same results. There is a variable 'RANDOM_START' that can be set to 0 to change this behavior.

**Comment by djmce** [comment]
Excellent, thanks @vibansal  
I cloned the repo, found this variable in `ancestry-gll.c`, set it to 0, ran `make all` and tested it;  confirmed via md5sum that identical outputs were obtained.

**Comment by djmce** [comment]
FYI, to get repeatable behaviour I also had to fix the seed to `srand48()` on line 416 of `ancestry-gll.c`

**Comment by vibansal** [comment]
Thanks for this update.
