### ISSUE TITLE
Code incompatibility with python 3

### ISSUE THREAD

**Issue by bapoorva** [vibansal/ancestry#15]
The runancestry.py file is incompatible with python 3 and needs tweaking to run. For instance the backticks in `POOLSIZE` in line 78

```
call([ executable_dir_path + "/calculateGLL --allsites 1 -p " + `POOLSIZE` + " --bam " + bamfile + " --variants " + outfile +".forGLL" + " --mmq 30 > " + outfile + ".GLL" ],shell=True)
```
and the print statements in line 82
```
print >>sys.stderr, "making input file for ancestry calculations"
```
instead of ```print("making input file for ancestry calculations")``` throws errors

**Comment by vibansal** [comment]
Yes, the code runs with Python 2.7 and is not compatible with Python 3. I should update the code to fix this. I have updated the readme to clarify this. Thanks.
