### ISSUE TITLE
Running ancestry with bam file

### ISSUE THREAD

**Issue by bapoorva** [vibansal/ancestry#16]
Hi,

You have mentioned in your documentation that to run iAdmix on bamfiles, we will need to run calculateGLL first to get the genotype likelihood ratio.Now calculate GLL requires a variant file as an argument. can you please specify the correct format of the variant file required to run calculateGLL. Or provide an example.

Thanks,
Apoorva

**Comment by vibansal** [comment]
To run iadmix on bamfiles, you need to use the python script. calculateGLL is run internally
