### ISSUE TITLE
where to find allelefreqs for hg38

### ISSUE THREAD

**Issue by avilella** [vibansal/ancestry#4]
Hi, I found about ancestry and I would like to know where to find an allelefreqs file for hg38. 

The one on DATA is for chr1 only and I presume it's hg19, as it does not find any useful fragments when tested against a hg38 bam.

Any ideas? thanks in advance.

**Comment by vibansal** [comment]
Hg19 allele frequency data from HapMap3 populations is available here: https://bansal-lab.github.io/software/hapmap3.8populations.hg19.zip 

I will convert it hg38 coordinates and upload the file soon.

**Comment by vibansal** [comment]
Allele frequency file with hg38 coordinates is available in the DATA sub-folder
